project_id: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /src/locales/**/*.po
    translation: /src/locales/%two_letters_code%/%original_file_name%
